-- MySQL Script generated by MySQL Workbench
-- Sun Jul  7 01:02:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`results` ;

CREATE TABLE IF NOT EXISTS `db`.`results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numCarsSelected` INT NOT NULL,
  `numDoorsSelected` VARCHAR(245) NOT NULL,
  `fuelTypeSelected` VARCHAR(245) NOT NULL,
  `carBodyStylesSelected` VARCHAR(245) NOT NULL,
  `driveTrainSelected` VARCHAR(245) NOT NULL,
  `numOfCylindersSelected` VARCHAR(245) NOT NULL,
  `budgetSelected` VARCHAR(245) NOT NULL,
  `carSizeSelected` VARCHAR(245) NOT NULL,
  `cityMPG` VARCHAR(245) NOT NULL,
  `hwyMPG` VARCHAR(245) NOT NULL,
  `car1Result` VARCHAR(245) NOT NULL,
  `car2Result` VARCHAR(245) NULL,
  `car3Result` VARCHAR(245) NULL,
  `car4Result` VARCHAR(245) NULL,
  `car5Result` VARCHAR(245) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `db`.`responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`responses` ;

CREATE TABLE IF NOT EXISTS `db`.`responses` (
  `id` INT NOT NULL,
  `selectedCar` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `db`.`results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
